### ISSUE TITLE
ACLModel#_processPermissions() calls BaseModel#formatTemplatedProperties instead of formatProperties

### ISSUE THREAD

**Issue by petetnt** [Everyplay/serverbone#29]
I was doing the `js-developer-assignment` and wondered why `ACLModel#_processPermissions()` was calling `BaseModel#formatTemplatedProperties` which turned out not to exists at all.

 `git bisect` says the functionality was added in [8a63297](https://github.com/Everyplay/serverbone/commit/8a63297) but `formatProperties` has always been called `formatProperties` instead of `formatTemplatedProperties`.

**Comment by Nomon** [comment]
That method is from further down the prototype chain, from backbone-blueprint, in the SchemaModel's prototype.

**Comment by petetnt** [comment]
Ah okay, that explains it! Thanks!
